language: python
sudo: false

python:
  - "2.7"
  - "3.5"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test tests --cov hanja --durations=10

after_success:
  - coveralls
