language: python
sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install "black; python_version >= '3.6'"
  - pip install -e .

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - |
    if [ -x "$(command -v black)" ]; then
      black --check .
    fi
  - py.test -v tests --cov hanja --cov-report term-missing

after_success:
  - coveralls
